version: '3.9'
services:
  nest:
    build: .
    container_name: api
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  db:
     image: mariadb:10.3.17
     container_name: db
     restart: always
     environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
     ports:
      - 3306:3306
     volumes:
         - .dbdata:/var/lib/mariadb